Feat/vtex category tree
deco-sites/std pull request #10
Opened 2023-03-17 12:34 UTC by lfroes

## What?

Added vtexCategoryTree client and loader so users can now get the categories for the current store

## Why?

Sometimes stores have a lot of categories, with that, you can skip the process of registering one by one and still control the order that these categories will appear

## How?

I created a new function on the client that gets the public API route from vtex `/api/catalog_system/pub/category/tree/{categoryLevels}`, after that I just created a handler on the loader that expects the user to put the name of the categories that he wants first it does not have this information it will follow the regular order received from VTEX

## Testing?

You can clone this repo and use it as std locally in your machine after that create a section that consumes this loader
e.g:

`import { Categories } from "deco-sites/std/commerce/types.ts";
 import type { LoaderReturnType } from "$live/types.ts";

export interface Props {
  categories: LoaderReturnType<Categories[] | null>;
}

function Menu({ categories }: Props) {
  return (
    <div className="menu">
      <div>
        {categories?.map((category: MenuItems, index: number) => {
          return (
            <div key={index}>
              {category.name}
            </div>
          );
        })}
      </div>
    </div>
  );
}

`

## Screenshots 
![image](https://user-images.githubusercontent.com/32175515/225904896-3a6d4056-86d0-4837-98f9-cb6a0e67af05.png)

##Anything Else?

thanx to @igorbrasileiro and @lucis for the support!

2023-03-17 12:58 UTC, lucis commented on functions/vtexProductList.ts
> +
Remove

2023-03-17 13:44 UTC, lfroes commented
Unfortunately, because of typing issues, these solutions didn't work, but I also asked to our mutual friend for some other solutions and make some changes in the code.

- Made the levels and categoriesOrder props optional and added default values.
- Removed the unnecessary console.log. (LOL)
- Converted the categories variable directly to Categories[].
- Combined the two forEach loops that update the category names.
- Reversed the categoriesOrder array before iterating over it.
- Simplified the code that hides categories and moves them to the beginning of the array.
- Replaced the map function with a forEach loop since the return value was not used.
- Made the function return early if there are no hidden categories.
- Removed the unnecessary type conversion at the end of the categoriesArray declaration.

Already been tested and is working fine!

2023-03-17 15:31 UTC, lfroes commented
Update: Changed the Loader to send All Categories (in case users want to make a "all-categories-options" in menu)

2023-03-17 17:04 UTC, mcandeia requested changes
Great work! The deco team appreciates your contribution

2023-03-17 17:04 UTC, mcandeia commented on functions/vtexCategoryTree.ts
> +  }
If I understood it correctly, looks like you're trying to hide categories based on what was specified at `categoriesOrder`.

Suggestion: (this is only a **suggestion** you do not implement if you think it is not necessary)
 create a map from the `categoriesOrder` object that maps from `categoryName` to `hideCategory` value it will result in something like this: Record<string, boolean>

```ts
const categoriesIndexed = categoriesOrder.reduce((categoryIndexed, {name, hideCategory}) => {
    return {...categoryIndexed, [name.toLowerCase().replace(/\s+/g, "-")]: hideCategory };
}, {} as Record<string, boolean>)
```

then you can just use `filter`

```ts
const finalCategories = categoriesArray.filter(category => !categoriesIndexed[category.name])
```

2023-03-17 17:06 UTC, mcandeia commented on functions/vtexCategoryTree.ts
> +  }
Well, just saw the @lucis message about the chatgpt suggestion. great! choose anything that works better for you!

2023-03-17 17:17 UTC, lfroes commented on commerce/types.ts
> +export interface Categories  {
Done, i was using the wrong formatter, thx

2023-03-17 17:19 UTC, lfroes commented on commerce/types.ts
> +
Done

2023-03-17 17:21 UTC, lfroes commented on functions/vtexCategoryTree.ts
> +}
Done

2023-03-17 17:25 UTC, lfroes commented on functions/vtexCategoryTree.ts
> +  });
I am glad you pointed that out. The second loop must be more on the bottom, the idea is just to control in case the user makes some typo error I could handle it. So the first loop we take out spaces and put - them in place of spaces. And in the second we just undo this to the return of the loader be easier to adjustments on CSS of the Front

2023-03-17 18:04 UTC, lfroes commented on functions/vtexCategoryTree.ts
> +  }
It looks great, i just have one question: How can I implement the "rev

2023-03-17 18:42 UTC, mcandeia approved these changes

2023-03-22 18:20 UTC, tlgimenes commented
Thanks for contributing @lfroes

2023-03-22 18:20 UTC, merged