New Butter CMS Loader
deco-sites/std pull request #47
Opened 2023-04-28 22:58 UTC by gustavo-vasconcellos

TBD

2023-05-06 18:01 UTC, mcandeia requested changes
Great job!

Additionally, I would appreciate your help to migrate the current functions implementation to the new loaders implementations: https://github.com/deco-sites/std/tree/main/loaders

Take this as an optional change.

2023-05-06 18:01 UTC, mcandeia commented on sections/configButterCMS.global.tsx
> +export default ConfigSection;
We have a new concept called `Accounts` which you can create an account inside `/accounts/` folder, that should have the same behavior as you want here but without need to mess up with your sections. 

Sadly, we don't have a documentation yet, so you can keep your global section if you want.

2023-05-07 20:56 UTC, gustavo-vasconcellos commented on commerce/butterCMS/client.ts
> +   */
@mcandeia Yes, it's intentional. I want to prevent misundestaning while filling the fields on Admin to avoid mistaskes on that field.

2023-05-07 20:58 UTC, gustavo-vasconcellos commented on commerce/butterCMS/client.ts
> +  authToken: string;
@mcandeia This authToken it's like a base64 string, so it's ok. Each locale have a different token, if there is some other ways that I can save and use on loaders, please guide me.

2023-05-07 21:02 UTC, gustavo-vasconcellos commented on functions/butterCMSPostDetail.ts
> +  const { data } = await client.post(slug);
@mcandeia They are blog articles, the `post` function it isn't about do a "POST method". There are `posts` - post's list - and `post` - get post - function on `client`.

2023-05-07 22:29 UTC, mcandeia commented on commerce/butterCMS/client.ts
> +  authToken: string;
Not sure if I understood you correctly, but base64 is just an encode method it’s not encryption, so you can take any base64 string and decode it right away without any key. So my advice still the same, this token will be publicly available when fulfilled

2023-05-07 22:30 UTC, mcandeia commented on functions/butterCMSPostDetail.ts
> +  const { data } = await client.post(slug);
I would rather prefer use  “getPosts”, but this is nitpicking

2023-05-08 19:31 UTC, merged